### ISSUE TITLE
U+263A Emoticon does not get detected or removed

### ISSUE THREAD

**Issue by roberterdin** [vdurmont/emoji-java#38]
The ☺(:relaxed:) emoji (U+263A), does not get removed if you call `EmojiParser::removeAllEmojis`. This is probably because it's in the 2600-26FF (Miscellaneous Symbols) block. At least android does encode the `:relaxed:` emoji as (U+263A).

**Comment by roberterdin** [comment]
Found the error, you have a U+FE0F Variance Selector which prevents it from being matched..., just remove it and the bug should be fixed.  Created you a pull request.

**Comment by roberterdin** [comment]
Fixed with #39

**Comment by iNPUTmice** [comment]
`U+263A` still doesn't get removed which causes EmojiManager.isOnlyEmoji() not to detect it as such.
Using 3.2.0 here. (Or maybe a regression. I haven't checked intermediate releases)

**Comment by vdurmont** [comment]
I just released 3.0.3 that contains https://github.com/vdurmont/emoji-java/pull/76 and it *should* fix it I think (I didn't test). It should be available on maven central in a few hours.

**Comment by iNPUTmice** [comment]
`U+263A` is still not recognized by `isOnlyEmoji()`. Since this is one of the old Unicode 1.1 'emoji' I'm not sure why the fitzpatric modifications from #76 should have anything to do with that. But than again I don't know anything about Unicode or Emoji…
